// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgSUNHh_UsP6rIK6HnVSoabc6EeuL8eEc',
    appId: '1:511172605197:web:8185b1f7767b28483aac44',
    messagingSenderId: '511172605197',
    projectId: 'upm-research',
    authDomain: 'upm-research.firebaseapp.com',
    storageBucket: 'upm-research.appspot.com',
    measurementId: 'G-9M1CNW42FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBooXS4ip8zjK-zJMmAv_f6XXZogjayKeA',
    appId: '1:511172605197:android:ed7054d81bc91cb63aac44',
    messagingSenderId: '511172605197',
    projectId: 'upm-research',
    storageBucket: 'upm-research.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSPhscqQ9bhZdkZcrjNuF3oWY3cKV2b9M',
    appId: '1:511172605197:ios:c90b6330a9e191d43aac44',
    messagingSenderId: '511172605197',
    projectId: 'upm-research',
    storageBucket: 'upm-research.appspot.com',
    iosBundleId: 'com.example.test6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSPhscqQ9bhZdkZcrjNuF3oWY3cKV2b9M',
    appId: '1:511172605197:ios:c90b6330a9e191d43aac44',
    messagingSenderId: '511172605197',
    projectId: 'upm-research',
    storageBucket: 'upm-research.appspot.com',
    iosBundleId: 'com.example.test6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgSUNHh_UsP6rIK6HnVSoabc6EeuL8eEc',
    appId: '1:511172605197:web:ee988a7c52ba69623aac44',
    messagingSenderId: '511172605197',
    projectId: 'upm-research',
    authDomain: 'upm-research.firebaseapp.com',
    storageBucket: 'upm-research.appspot.com',
    measurementId: 'G-C8XT6FH2T6',
  );
}
